version: '3.8'
services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: database

  server:
    container_name: server
    depends_on:
      - database
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - 4000:4000

  web:
    container_name: web
    ports:
      - 3000:3000
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - server

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  db-data:
  pgadmin-data:
